project:
  type: website
  output-dir: docs  # folder where HTML files will be saved

website:
  title: "Bayesian Logistic Regression - Application in Probability Prediction of Disease (Diabetes)"
subtitle: "CapStone Project 2025"
navbar:
    left:
      - text: "Research"
        href: index.qmd
      - text: "Slides"
        href: slides.qmd
      - text: "About Us"
        href: about.qmd

format:
  html:
    theme: flatly
    toc: true
    code-fold: true
    page-layout: full
    self-contained: true
